eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server :
  port : 8891
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic